default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: shop-app-development

test:
  <<: *default
  database: shop-app-test

production:
  <<: *default
  database: shopping-app-production
  username: shopping-app
  password: <%= ENV['SHOPPING-APP_DATABASE_PASSWORD'] %>
